#!/bin/bash
###########################################################################
# Description:
#     This script will launch the python script of the BGP Ping Mesh agent
#     (forwarding any arguments passed to this script).
#
# Copyright (c) 2018-2021 Nokia, generated by srl-agent-builder
###########################################################################


_term (){
    echo "Caugth signal SIGTERM !! "
    kill -TERM "$child" 2>/dev/null
}

function main()
{
    trap _term SIGTERM
    local virtual_env="/opt/bgp-ping-mesh/.venv/bin/activate"
    local main_module="/opt/bgp-ping-mesh/bgp-ping-mesh.py"

    # source the virtual-environment, which is used to ensure the correct python packages are installed,
    # and the correct python version is used
    source "${virtual_env}"

    # Opening srbase-default namespace requires root
    python3 ${main_module} &

    child=$!
    wait "$child"
}

main "$@"
